### ISSUE TITLE
Include original feed title

### ISSUE THREAD

**Issue by Boddlnagg** [spenibus/rss-filter-php#1]
Hi! This script is great, thanks for sharing it!

It would be great if the title of the filtered feed would not always be `rss-filter`, but something more descriptive, either matching or containing the original feed title (e.g. `<Original Title> (filtered)`). Some feedreaders do not allow user-defined feed titles, which means that I have multiple feeds called `rss-filter`, and those can't be distinguished.

**Comment by spenibus** [comment]
As I only use this script for automated tasks, I never had a use for the title. I recognize however that it would be useful.

Feature added in 417f45b69193d8d5d4b6b35a4479556662c88eed.
