### ISSUE TITLE
Filter by category

### ISSUE THREAD

**Issue by kriegaex** [spenibus/rss-filter-php#2]
Hi,

I just found your nice script and tried it on my webserver. I managed to get it running. So far, so good.

Now I tried to migrate my filtering rules from an online filtering service which has some technical problems to this self-hosted solution. Unfortunately, while some of my filters only are OK with filtering the title, others rely on `category` tags. I wonder if you could add the capability of filtering by category (or maybe even by arbitrary tags, as named in the config file) to your product.

_About myself: I speak Java, Groovy and a few other programming languages, but no PHP or Python. The latter two are the only ones available on my shared hosting server, which is why I am using your script in the first place, because I cannot develop anything by myself without learning a new language. Maybe I could add the feature using come copy-past-modify approach, hacking an extension into your script, but I guess that a clean solution by an experienced PHP programmer is preferable. If I wanted to do it myself in PHP, I could just use [SimplePie](https://github.com/simplepie/simplepie/), which is a library rather than a configurable solution._

**Comment by kriegaex** [comment]
I have reviewed the code a bit and also hacked some more filters into it, trying to extend the existing scheme. Actually, I think the way it works is quite contrived, even though it means to be simple. Maybe it is my way of thinking or the kind of filter logic I need, but with the existing code structure, I cannot get it done. This is not so much about the programming language as such, but really about the algorithm. I would prefer some clear boolean logic without any structural limitations, e.g. a configuration with a single filter rule containinga single bolean operation and arbitrarily nestable sub-operations like:

```xml
<filterRule>
  <and>
    <or>
      <title>{regex1}<title>
      <title>{regex2}<title>
      <category>{regex3}<title>
    </or>
    <category>{regex4}<title>
    <not>
      <category>{regex5}<title>
    </not>
    <not>
      <and>
        <category>{regex6}<title>
        <title>{regex7}<title>
      </and>
    </not>
  </and>
</filterRule>
```

This would be equivalent with (pseudo code):
```java
(title.matches(regex1) OR title.matches(regex2) OR category.matches(regex1))
  AND category.matches(regex4)
  AND NOT (category.matches(regex5))
  AND NOT (category.matches(regex6) AND title.matches(regex7))
```

Of course, that would require more generic XML-to-action mapping and permit for recursion, because we have nesting here. But OTOH, we could avoid special operations like `titleMatchMust` and `titleMatchNot` and the same again for `<category>` or `<description>` tags. For each tag, we could generically use the same tag in the configuration, and each tag value would always be a regex. Some added complexity would be the requirement to loop over tags which can appear multiple times like the category and to report a positive match, if any of the tags matches (i.e. an implicit OR condition). If you think about it, even this is generic, because a tag appearing exactly once is simply a special case of `myTag.matches(myRegex) OR true`.

Sorry if this all sounds a bit theoretical, I am mostly thinking aloud. I know how I would implement it in another language like Groovy or Java, but in PHP it would require a lot of trial & error.

I also know that your 3 types of conditions for the title is something resembling boolean conditions, but then again you have multiple rules in a rule set, chaining them in some kind of logical OR, but not exactly. The results are hard to predict, despite your documentation, because you invent your own logical scheme instead of simply using boolean conditions.

**Comment by spenibus** [comment]
It was indeed made a long time ago for my specific needs. While I generally tend to prefer generic solutions as well, it would have been overkill at the time.

As much as I enjoy a good refactoring, the harsh reality is that this is a lot of work on top of my day job and I'm already not sleeping enough.

I'm having a look at the source (with all the bafflement of reading one's code years later) and it seems extending the config structure and which rss tags to look up would be fairly simple. The real issue is indeed the actual processing.

I've got a couple of ideas but I just don't have the time.

    Raw notes
    ---------
    <and> // aggregate all nested result
    <or> // aggregate nested results, stop on first positive
    <match tag=""></match> // tag: * (all), tagName, csv support ?
    <matchNot tag=... // shorthand, less nesting than <not> ?
    <not> // flip the aggregate result of nested results
    // "not" could also be an attribute, applicable to all config keywords
    // same for "tag"
    <match not tag="...">
    <and not>
    // "not" applies to rules and blocks (can retrofit old keywords such as date/time handling)
    // "tag" applies to rules only
    // might need <ruleset mode="2"> to apply separate engine, new date/time keywords, etc

Thinking aloud indeed. But expectations must be lowered, I'm tired and busy.

**Comment by kriegaex** [comment]
Oh, I just noticed that I can put more than one identical tags into one `rules` section, e.g.

```xml
<rules>
  <titleMatchNot>/[0-9]+ (best|top secret)/si</titleMatchNot>
  <titleMatchNot>/top [0-9]+/si</titleMatchNot>
  <categoryMatchNot>/product reviews/si</categoryMatchNot>
  <categoryMatchNot>/best of/si</categoryMatchNot>
</rules>
```

It looks like this works similar to AND, while multiple parallel rules are more like OR. In your examples and tests you never have the same tag more than once, so I thought it was forbidden and unneffective. Now I kind of achieved the kind of filter rules that I  personally need, i.e. waiting for you to implement the more general parsing and evaluation scheme gets easier for me. As you can see above, I added category filtering, because this is what scratches my personal itch for the moment. I can create a PR, but don't expect it to be beautiful. Like I said, I never touched any PHP code before in my life.

**Comment by kriegaex** [comment]
Sorry for the many commits listed above. Actually, it was a single commmit, but I had to figure out why the two changed files always were full diffs. It was due to the fact that you committed with CRLF line endings instead of the Git default LF. You seem to have Git configured to not convert them, i.e. it is a Windows-only project. I had to match my fork's local Git configuration in order to produce smaller diffs.

**Comment by kriegaex** [comment]
What are we going to do with this ticket? Actually, my PR closes it with regard to category matching. But we talked about a more general refactoring here, too. Should we extract our notes, both yours and mine, into a new issue and close this one instead? I do not know how you organise your projects.

**Comment by kriegaex** [comment]
FYI, the two force-pushes here fixed a small bug and optimised something else. Because you have not started reviewing the PR, I thought I would just keep everything in one commit.

**Comment by kriegaex** [comment]
FYI, the two force-pushes here fixed a small bug and optimised something else. Because you have not started reviewing the PR, I thought I would just keep everything in one commit. But now I think I am done.

**Comment by spenibus** [comment]
Need to find some time to do code review but it looks fairly clean.

Generic matching would indeed be better at home in its own ticket (#4).

Looks like I did not specify rules keywords can appear multiple times in rules blocks, probably "very obvious" when I wrote it. I merely implied it:

> when at least one `keyword` ...

Thinking back, crude boolean emulation is the reason multiple `rules` blocks are allowed within a `ruleset`.

CRLF behaviour must be an old setting from the very first time Git was installed.

**Comment by kriegaex** [comment]
> Need to find some time to do code review but it looks fairly clean.
> 
> Generic matching would indeed be better at home in its own ticket (#4).
> 
> Looks like I did not specify rules keywords can appear multiple times in rules blocks, probably "very obvious" when I wrote it. I merely implied it:
> 
> > when at least one `keyword` ...

In combination with the config structure and the examples, I thought that "at least one" applied to the situation of multiple `rules` sections within one `ruleSet`. I might add one more commit to the PR, adding a bit more information to the read-me file.

**Comment by kriegaex** [comment]
This PR is one month old now. Given the fact that you seem to be to busy to conduct a little code review and merge this PR, is it sage to assume that the project is basically retired and should be forked, instead of taking the trouble to create and bother you with PRs?

**Comment by spenibus** [comment]
My office kinda doubles as a workshop and let's just say my desk was unusable until a recent clean-up.

Anyway, everything looks fine so that's a green light, I just need to check my local setup first, it seems I have some issues with my multiple remotes.

**Comment by spenibus** [comment]
Done #3.

**Comment by kriegaex** [comment]
Thank you very much. 🙂 One less item on my backlog to follow up on.
